version: "2"

linters:
  # Enable ALL linters by default, disable only those that don't apply
  default: all

  disable:
    # Deprecated linters
    - wsl               # Replaced by wsl_v5

    # Don't apply to this project
    - depguard          # Requires allowlist config - not useful for small CLI
    - gochecknoglobals  # We use globals for version, styles, patterns
    - exhaustruct       # Too strict - not all struct fields need initialization
    - ireturn           # "Return concrete types" - doesn't apply to View interface pattern
    - gosmopolitan      # i18n checks - not needed for CLI tool

    # Too opinionated / style preferences
    - varnamelen        # Variable name length limits
    - godot             # Period at end of comments

    # Noise for TUI/CLI code
    - mnd               # Magic numbers - TUI has many dimension constants

    # False positives / not useful
    - durationcheck     # False positive on h * time.Hour pattern
    - err113            # Too strict - dynamic errors with context are fine for CLI

  exclusions:
    rules:
      # Exclude some linters from test files
      - path: _test\.go
        linters:
          - gosec
          - errcheck
          - err113
          - forcetypeassert

  settings: {}

formatters:
  enable:
    - gofmt
    - goimports
