apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: watch-rollout
spec:
  version: {{ .TagName }}
  homepage: https://github.com/ivoronin/kubectl-watch-rollout
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/ivoronin/kubectl-watch-rollout/releases/download/{{ .TagName }}/kubectl-watch-rollout_{{ .TagName }}_linux_amd64.tar.gz" .TagName }}
    files:
    - from: kubectl-watch-rollout
      to: "."
    - from: LICENSE
      to: "."
    bin: kubectl-watch-rollout
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    {{addURIAndSha "https://github.com/ivoronin/kubectl-watch-rollout/releases/download/{{ .TagName }}/kubectl-watch-rollout_{{ .TagName }}_linux_arm64.tar.gz" .TagName }}
    files:
    - from: kubectl-watch-rollout
      to: "."
    - from: LICENSE
      to: "."
    bin: kubectl-watch-rollout
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/ivoronin/kubectl-watch-rollout/releases/download/{{ .TagName }}/kubectl-watch-rollout_{{ .TagName }}_darwin_amd64.tar.gz" .TagName }}
    files:
    - from: kubectl-watch-rollout
      to: "."
    - from: LICENSE
      to: "."
    bin: kubectl-watch-rollout
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    {{addURIAndSha "https://github.com/ivoronin/kubectl-watch-rollout/releases/download/{{ .TagName }}/kubectl-watch-rollout_{{ .TagName }}_darwin_arm64.tar.gz" .TagName }}
    files:
    - from: kubectl-watch-rollout
      to: "."
    - from: LICENSE
      to: "."
    bin: kubectl-watch-rollout
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/ivoronin/kubectl-watch-rollout/releases/download/{{ .TagName }}/kubectl-watch-rollout_{{ .TagName }}_windows_amd64.zip" .TagName }}
    files:
    - from: kubectl-watch-rollout.exe
      to: "."
    - from: LICENSE
      to: "."
    bin: kubectl-watch-rollout.exe
  - selector:
      matchLabels:
        os: windows
        arch: arm64
    {{addURIAndSha "https://github.com/ivoronin/kubectl-watch-rollout/releases/download/{{ .TagName }}/kubectl-watch-rollout_{{ .TagName }}_windows_arm64.zip" .TagName }}
    files:
    - from: kubectl-watch-rollout.exe
      to: "."
    - from: LICENSE
      to: "."
    bin: kubectl-watch-rollout.exe
  shortDescription: Watch Kubernetes deployment rollouts with live progress
  description: |
    kubectl watch-rollout monitors Kubernetes deployment rollouts in real-time,
    displaying progress bars, pod status, warnings, and completion estimates.

    Features:
    - Real-time progress bars for new and old ReplicaSets
    - Pod status counts (Available, Ready, Current)
    - Warning events from pods with aggregation
    - Estimated time to completion
    - Progress deadline tracking
    - Automatic detection of rollout success or failure
    - Auto-discovery mode for active rollouts
