name: goreleaser

on:
  pull_request:
  push:

permissions:
  contents: write

jobs:
  goreleaser:
    env:
      GORELEASER_FLAGS:
    runs-on: ubuntu-latest
    steps:
      -
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: echo "GORELEASER_FLAGS=--snapshot" >> $GITHUB_ENV
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean ${{ env.GORELEASER_FLAGS }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Update krew-index
        if: startsWith(github.ref, 'refs/tags/v')
        uses: rajatjindal/krew-release-bot@v0.0.46
